### ISSUE TITLE
Cannot start Visualizer (Panic)

### ISSUE THREAD

**Issue by shadowcpy** [Rahix/visualizer2#1]
Every visualizer panics, when trying to run:
```
Oh noez! Panic! 💥
Message:  attempted to leave type platform::platform::x11::util::input::PointerState uninitialized, which is invalid```

**Comment by Rahix** [comment]
Thanks for the report!  I've pushed some commits to fix this - it seems that the old winit version I was using bit-rotted and I needed to upgrade...

**Comment by shadowcpy** [comment]
Thanks, that fixed it! One more question, how do I set the input source? There is no example config (visualizer.toml) provided.

Thanks you for your work!

**Comment by Rahix** [comment]
Actually, I'm always just using `pavucontrol` and switching it in the _Recording_ tab...

**Comment by shadowcpy** [comment]
Works, thanks for your help!
