### ISSUE TITLE
How to run live mode

### ISSUE THREAD

**Issue by e-tornike** [Rahix/visualizer2#5]
Hey there, how would I run the most basic live mode configuration with pulseaudio input?

**Comment by Rahix** [comment]
Not sure what your question is, exactly?  To run e.g. the _noambition_ visualizer, just do

```
cd noambition/
cargo run --release
```

this will use cpal by default:

https://github.com/Rahix/visualizer2/blob/512e02ebe092ea2e87655fe22f925d0f27e5f0c3/noambition/visualizer.toml#L6

cpal uses ALSA and usually pulseaudio provides an ALSA compatibility layer so your audio will be recorded from pulseaudio.

You may need to use `pavucontrol` or another tool to hook up the visualizer to the monitor of your audio output.  Or connect it to the correct microphone, if you want to visualize music played from outside sources.

**Comment by e-tornike** [comment]
I see. It works with the input from the microphone but not from audio played by the system itself.

**Comment by Rahix** [comment]
In `pavucontrol`, in the _Recording_ tab, you have to set the source of the visualizer's audio input to _Monitor of \[your audio output device]_.  Then it will visualize the audio played by the system itself.

**Comment by e-tornike** [comment]
That works. Thanks a lot for the help!
